/**
 * SINH TỰ ĐỘNG TỪ `ALL_FORMULAS` — ĐỪNG SỬA TAY.
 * Sinh lại bằng: npm run gen:summaries
 *
 * Đây là chỉ mục nhẹ cho màn duyệt và tìm: chỉ tên, mô tả, thẻ và cấp độ. Cố tình KHÔNG
 * import gì từ các module công thức, để trang danh sách không phải tải diễn giải, ví dụ,
 * ca kiểm thử và hàm tính của toàn bộ Registry (NFR-PER-04).
 *
 * `summaries.test.ts` đối chiếu file này với Registry thật sau mỗi lần chạy test, nên nó
 * không thể lệch mà không ai biết.
 */

import type { FormulaSummary } from '../registry/types';

export const FORMULA_SUMMARIES: ReadonlyArray<FormulaSummary> = [
  {
    id: 'pe',
    categoryId: 'fundamentals',
    name: { vi: 'P/E — hệ số giá trên lợi nhuận', en: 'Price to earnings ratio' },
    description: 'Nhà đầu tư trả bao nhiêu đồng cho mỗi đồng lợi nhuận của doanh nghiệp.',
    level: 'basic',
    isFeatured: true,
    tags: ['pe', 'p e', 'gia tren loi nhuan', 'boi so', 'dinh gia'],
  },
  {
    id: 'pb',
    categoryId: 'fundamentals',
    name: { vi: 'P/B — hệ số giá trên giá trị sổ sách', en: 'Price to book ratio' },
    description: 'Thị giá đang gấp bao nhiêu lần giá trị sổ sách của một cổ phiếu.',
    level: 'basic',
    isFeatured: true,
    tags: ['pb', 'p b', 'gia tren gia tri so sach', 'boi so'],
  },
  {
    id: 'eps-co-ban',
    categoryId: 'fundamentals',
    name: { vi: 'EPS cơ bản', en: 'Basic earnings per share' },
    description: 'Mỗi cổ phiếu phổ thông làm ra bao nhiêu đồng lợi nhuận trong kỳ.',
    level: 'basic',
    tags: ['eps', 'loi nhuan tren co phieu', 'earnings per share', 'chi so dn'],
  },
  {
    id: 'bvps',
    categoryId: 'fundamentals',
    name: { vi: 'BVPS — giá trị sổ sách mỗi cổ phiếu', en: 'Book value per share' },
    description: 'Mỗi cổ phiếu đang nắm giữ bao nhiêu đồng vốn chủ sở hữu trên sổ sách.',
    level: 'basic',
    tags: ['bvps', 'gia tri so sach', 'book value', 'chi so dn'],
  },
  {
    id: 'roe',
    categoryId: 'fundamentals',
    name: { vi: 'ROE — tỷ suất sinh lời trên vốn chủ', en: 'Return on equity' },
    description: 'Một đồng vốn của cổ đông làm ra bao nhiêu đồng lợi nhuận trong một năm.',
    level: 'basic',
    tags: ['roe', 'ty suat sinh loi', 'von chu so huu', 'return on equity', 'chi so dn'],
  },
  {
    id: 'roa',
    categoryId: 'fundamentals',
    name: { vi: 'ROA — tỷ suất sinh lời trên tài sản', en: 'Return on assets' },
    description: 'Một đồng tài sản của doanh nghiệp tạo ra bao nhiêu đồng lợi nhuận.',
    level: 'basic',
    tags: ['roa', 'ty suat sinh loi', 'tong tai san', 'return on assets', 'chi so dn'],
  },
  {
    id: 'bien-loi-nhuan-rong',
    categoryId: 'fundamentals',
    name: { vi: 'ROS — biên lợi nhuận ròng', en: 'Net profit margin' },
    description: 'Cứ 100 đồng doanh thu thì doanh nghiệp giữ lại được bao nhiêu đồng lãi ròng.',
    level: 'basic',
    tags: ['ros', 'bien loi nhuan rong', 'net margin', 'profit margin', 'chi so dn'],
  },
  {
    id: 'bien-loi-nhuan-gop',
    categoryId: 'fundamentals',
    name: { vi: 'Biên lợi nhuận gộp', en: 'Gross profit margin' },
    description: 'Phần trăm doanh thu còn lại sau khi trừ giá vốn hàng bán.',
    level: 'basic',
    tags: ['bien loi nhuan gop', 'gross margin', 'gia von', 'chi so dn'],
  },
  {
    id: 'no-tren-von-chu',
    categoryId: 'fundamentals',
    name: { vi: 'D/E — hệ số nợ trên vốn chủ', en: 'Debt to equity ratio' },
    description: 'Doanh nghiệp đang vay bao nhiêu đồng nợ trên mỗi đồng vốn của cổ đông.',
    level: 'basic',
    tags: ['de', 'd e', 'no tren von chu', 'don bay', 'debt to equity', 'chi so dn'],
  },
  {
    id: 'thanh-toan-hien-hanh',
    categoryId: 'fundamentals',
    name: { vi: 'Hệ số thanh toán hiện hành', en: 'Current ratio' },
    description: 'Tài sản ngắn hạn gấp bao nhiêu lần nợ phải trả trong 12 tháng tới.',
    level: 'basic',
    tags: ['thanh toan hien hanh', 'current ratio', 'thanh khoan', 'chi so dn'],
  },
  {
    id: 'thanh-toan-nhanh',
    categoryId: 'fundamentals',
    name: { vi: 'Hệ số thanh toán nhanh', en: 'Quick ratio' },
    description: 'Khả năng trả nợ ngắn hạn khi không kịp bán hàng tồn kho.',
    level: 'basic',
    tags: ['thanh toan nhanh', 'quick ratio', 'acid test', 'thanh khoan', 'chi so dn'],
  },
  {
    id: 'vong-quay-tong-tai-san',
    categoryId: 'fundamentals',
    name: { vi: 'Vòng quay tổng tài sản', en: 'Total asset turnover' },
    description: 'Một đồng tài sản tạo ra bao nhiêu đồng doanh thu trong một năm.',
    level: 'basic',
    tags: ['vong quay tai san', 'asset turnover', 'hieu suat', 'chi so dn'],
  },
  {
    id: 'ty-le-chi-tra-co-tuc',
    categoryId: 'fundamentals',
    name: { vi: 'Hệ số chi trả cổ tức', en: 'Dividend payout ratio' },
    description: 'Doanh nghiệp đem bao nhiêu phần trăm lợi nhuận ra trả cổ tức tiền mặt.',
    level: 'basic',
    tags: ['chi tra co tuc', 'payout ratio', 'co tuc', 'dps', 'chi so dn'],
  },
  {
    id: 'ps',
    categoryId: 'valuation',
    name: { vi: 'P/S — hệ số giá trên doanh thu', en: 'Price to sales ratio' },
    description: 'Nhà đầu tư trả bao nhiêu đồng cho mỗi đồng doanh thu của doanh nghiệp.',
    level: 'basic',
    tags: ['ps', 'p s', 'gia tren doanh thu', 'boi so', 'dinh gia', 'price to sales'],
  },
  {
    id: 'ev',
    categoryId: 'valuation',
    name: { vi: 'EV — giá trị doanh nghiệp', en: 'Enterprise value' },
    description: 'Số tiền cần bỏ ra để mua trọn doanh nghiệp, gồm cả nợ và trừ đi tiền mặt.',
    level: 'basic',
    tags: ['ev', 'gia tri doanh nghiep', 'enterprise value', 'von hoa', 'no vay'],
  },
  {
    id: 'ev-ebitda',
    categoryId: 'valuation',
    name: { vi: 'EV/EBITDA', en: 'EV to EBITDA ratio' },
    description: 'Giá mua trọn doanh nghiệp gấp bao nhiêu lần lợi nhuận trước lãi vay, thuế và khấu hao.',
    level: 'advanced',
    isFeatured: true,
    tags: ['ev ebitda', 'boi so', 'dinh gia', 'khau hao', 'enterprise multiple'],
  },
  {
    id: 'ev-sales',
    categoryId: 'valuation',
    name: { vi: 'EV/Sales — EV trên doanh thu', en: 'EV to sales ratio' },
    description: 'Giá mua trọn doanh nghiệp gấp bao nhiêu lần doanh thu một năm.',
    level: 'advanced',
    tags: ['ev sales', 'ev doanh thu', 'boi so', 'dinh gia', 'ev to sales'],
  },
  {
    id: 'peg',
    categoryId: 'valuation',
    name: { vi: 'PEG — P/E trên tăng trưởng', en: 'Price/earnings to growth ratio' },
    description: 'P/E đã chia cho tốc độ tăng trưởng lợi nhuận, để so cổ phiếu tăng trưởng với nhau.',
    level: 'advanced',
    tags: ['peg', 'tang truong', 'boi so', 'dinh gia', 'growth'],
  },
  {
    id: 'von-hoa-thi-truong',
    categoryId: 'valuation',
    name: { vi: 'Vốn hoá thị trường', en: 'Market capitalisation' },
    description: 'Tổng giá trị thị trường của toàn bộ cổ phiếu đang lưu hành.',
    level: 'basic',
    isFeatured: true,
    tags: ['von hoa', 'market cap', 'quy mo', 'gia tri thi truong'],
  },
  {
    id: 'so-graham',
    categoryId: 'valuation',
    name: { vi: 'Số Graham', en: 'Graham number' },
    description: 'Mức giá tối đa Benjamin Graham cho là hợp lý, dựa trên EPS và giá trị sổ sách.',
    level: 'advanced',
    tags: ['so graham', 'graham number', 'gia tri noi tai', 'dau tu gia tri', 'value investing'],
  },
  {
    id: 'ncav-tren-co-phieu',
    categoryId: 'valuation',
    name: { vi: 'NCAV trên cổ phiếu', en: 'Net current asset value per share' },
    description: 'Giá trị tài sản ngắn hạn còn lại cho mỗi cổ phiếu sau khi trả hết mọi khoản nợ.',
    level: 'advanced',
    tags: ['ncav', 'net net', 'graham', 'tai san ngan han', 'dau tu gia tri'],
  },
  {
    id: 'ty-suat-loi-nhuan-tren-gia',
    categoryId: 'valuation',
    name: { vi: 'Tỷ suất lợi nhuận trên giá', en: 'Earnings yield' },
    description: 'Mỗi 100 đồng bỏ ra mua cổ phiếu đang tạo ra bao nhiêu đồng lợi nhuận — nghịch đảo của P/E.',
    level: 'basic',
    tags: ['earnings yield', 'ty suat loi nhuan', 'nghich dao pe', 'e p', 'so voi lai suat'],
  },
  {
    id: 'gia-muc-tieu',
    categoryId: 'valuation',
    name: { vi: 'Giá mục tiêu', en: 'Target price' },
    description: 'Mức giá kỳ vọng nếu thị trường định giá cổ phiếu theo đúng P/E mục tiêu đã chọn.',
    level: 'basic',
    tags: ['gia muc tieu', 'target price', 'dinh gia', 'pe muc tieu'],
  },
  {
    id: 'mo-hinh-gordon',
    categoryId: 'valuation',
    name: { vi: 'Mô hình Gordon (DDM một giai đoạn)', en: 'Gordon growth model' },
    description: 'Giá trị cổ phiếu từ dòng cổ tức tăng trưởng đều mãi mãi, chiết khấu về hiện tại.',
    level: 'advanced',
    tags: ['gordon', 'ddm', 'chiet khau co tuc', 'dinh gia co tuc', 'dividend discount'],
  },
  {
    id: 'ddm-hai-giai-doan',
    categoryId: 'valuation',
    name: { vi: 'DDM hai giai đoạn', en: 'Two-stage dividend discount model' },
    description: 'Giá trị cổ phiếu khi cổ tức tăng nhanh vài năm đầu rồi chuyển về tăng trưởng đều dài hạn.',
    level: 'advanced',
    tags: ['ddm hai giai doan', 'two stage ddm', 'chiet khau co tuc', 'tang truong hai giai doan'],
  },
  {
    id: 'capm',
    categoryId: 'valuation',
    name: { vi: 'CAPM — chi phí vốn chủ sở hữu', en: 'Capital asset pricing model' },
    description: 'Suất sinh lợi yêu cầu của cổ đông, tính từ lãi suất phi rủi ro và hệ số beta.',
    level: 'advanced',
    tags: ['capm', 'chi phi von chu', 'beta', 'phan bu rui ro', 'cost of equity'],
  },
  {
    id: 'wacc',
    categoryId: 'valuation',
    name: { vi: 'WACC — chi phí vốn bình quân gia quyền', en: 'Weighted average cost of capital' },
    description: 'Chi phí huy động một đồng vốn của doanh nghiệp, trộn giữa vốn chủ và nợ vay sau lá chắn thuế.',
    level: 'advanced',
    tags: ['wacc', 'chi phi von binh quan', 'co cau von', 'la chan thue', 'cost of capital'],
  },
  {
    id: 'fcff',
    categoryId: 'valuation',
    name: { vi: 'FCFF — dòng tiền tự do của doanh nghiệp', en: 'Free cash flow to firm' },
    description: 'Tiền còn lại cho cả chủ nợ lẫn cổ đông sau thuế và sau khi tái đầu tư, tính từ EBIT.',
    level: 'advanced',
    tags: ['fcff', 'dong tien tu do', 'ebit', 'dcf', 'free cash flow'],
  },
  {
    id: 'fcfe',
    categoryId: 'valuation',
    name: { vi: 'FCFE — dòng tiền tự do của cổ đông', en: 'Free cash flow to equity' },
    description: 'Tiền còn lại riêng cho cổ đông sau khi trả lãi vay sau thuế và điều chỉnh vay nợ ròng.',
    level: 'advanced',
    tags: ['fcfe', 'dong tien tu do co dong', 'dcf', 'free cash flow to equity'],
  },
  {
    id: 'gia-tri-noi-tai-fcff',
    categoryId: 'valuation',
    name: { vi: 'Giá trị nội tại từ FCFF (DCF)', en: 'Intrinsic value from FCFF' },
    description: 'Chiết khấu dòng tiền tự do của doanh nghiệp bằng WACC, trừ nợ ròng, chia cho số cổ phiếu.',
    level: 'advanced',
    tags: ['dcf', 'gia tri noi tai', 'chiet khau dong tien', 'fcff', 'intrinsic value'],
  },
  {
    id: 'gia-tri-hien-tai',
    categoryId: 'valuation',
    name: { vi: 'Giá trị hiện tại (PV)', en: 'Present value' },
    description: 'Một khoản tiền trong tương lai đáng giá bao nhiêu ở hôm nay.',
    level: 'basic',
    tags: ['pv', 'gia tri hien tai', 'chiet khau', 'present value'],
  },
  {
    id: 'gia-tri-tuong-lai',
    categoryId: 'valuation',
    name: { vi: 'Giá trị tương lai (FV)', en: 'Future value' },
    description: 'Một khoản tiền hôm nay lớn thành bao nhiêu sau nhiều năm sinh lợi kép.',
    level: 'basic',
    tags: ['fv', 'gia tri tuong lai', 'lai gop', 'future value'],
  },
  {
    id: 'bien-an-toan',
    categoryId: 'valuation',
    name: { vi: 'Biên an toàn', en: 'Margin of safety' },
    description: 'Thị giá đang thấp hơn giá trị nội tại ước tính bao nhiêu phần trăm.',
    level: 'basic',
    isFeatured: true,
    tags: ['bien an toan', 'margin of safety', 'gia tri noi tai', 'graham', 'dinh gia'],
  },
  {
    id: 'phi-giao-dich-mua',
    categoryId: 'fees-tax',
    name: { vi: 'Phí giao dịch mua', en: 'Buy-side brokerage fee' },
    description: 'Phí công ty chứng khoán thu khi lệnh mua khớp.',
    level: 'basic',
    tags: ['phi mua', 'phi moi gioi', 'phi giao dich'],
  },
  {
    id: 'phi-giao-dich-ban',
    categoryId: 'fees-tax',
    name: { vi: 'Phí giao dịch bán', en: 'Sell-side brokerage fee' },
    description: 'Phí công ty chứng khoán thu khi lệnh bán khớp.',
    level: 'basic',
    tags: ['phi ban', 'phi moi gioi', 'phi giao dich'],
  },
  {
    id: 'thue-chuyen-nhuong',
    categoryId: 'fees-tax',
    name: { vi: 'Thuế chuyển nhượng chứng khoán', en: 'Securities transfer tax' },
    description: 'Thuế thu nhập cá nhân tính trên giá trị bán, thu cả khi giao dịch lỗ.',
    level: 'basic',
    tags: ['thue', 'thue cnck', 'chuyen nhuong'],
  },
  {
    id: 'thue-co-tuc',
    categoryId: 'fees-tax',
    name: { vi: 'Thuế cổ tức tiền mặt', en: 'Cash dividend tax' },
    description: 'Thuế khấu trừ trên cổ tức tiền mặt trước khi tiền về tài khoản.',
    level: 'basic',
    tags: ['thue co tuc', 'co tuc', 'dividend'],
  },
  {
    id: 'phi-luu-ky',
    categoryId: 'fees-tax',
    name: { vi: 'Phí lưu ký', en: 'Custody fee' },
    description: 'Phí giữ hộ cổ phiếu, tính theo số cổ phiếu và số tháng nắm giữ.',
    level: 'basic',
    tags: ['phi luu ky', 'vsd', 'custody'],
  },
  {
    id: 'gia-hoa-von',
    categoryId: 'fees-tax',
    name: { vi: 'Giá hoà vốn thực', en: 'True break-even price' },
    description: 'Giá bán tối thiểu để không lỗ sau khi trừ hết phí và thuế.',
    level: 'basic',
    isFeatured: true,
    tags: ['gia hoa von', 'hoa von', 'break even'],
  },
  {
    id: 'loi-nhuan-rong',
    categoryId: 'fees-tax',
    name: { vi: 'Lợi nhuận ròng sau phí & thuế', en: 'Net profit after fees and taxes' },
    description: 'Số tiền lãi thực sự còn lại sau khi trừ hết phí giao dịch và thuế.',
    level: 'basic',
    isFeatured: true,
    tags: ['loi nhuan rong', 'lai rong', 'phi va thue'],
  },
  {
    id: 'roi-rong',
    categoryId: 'fees-tax',
    name: { vi: 'ROI ròng sau phí & thuế', en: 'Net ROI after fees and taxes' },
    description: 'Tỷ suất lợi nhuận thực trên số vốn đã thực sự bỏ ra.',
    level: 'basic',
    tags: ['roi rong', 'ty suat loi nhuan', 'hieu qua'],
  },
  {
    id: 'roi',
    categoryId: 'returns',
    name: { vi: 'ROI — tỷ suất lợi nhuận', en: 'Return on investment' },
    description: 'Phần trăm lãi hoặc lỗ so với số vốn đã bỏ ra.',
    level: 'basic',
    isFeatured: true,
    tags: ['roi', 'ty suat loi nhuan', 'hieu qua dau tu'],
  },
  {
    id: 'hpr',
    categoryId: 'returns',
    name: { vi: 'HPR — lợi suất kỳ nắm giữ', en: 'Holding period return' },
    description: 'Lợi suất một kỳ nắm giữ, tính cả chênh lệch giá lẫn cổ tức nhận được.',
    level: 'basic',
    tags: ['hpr', 'loi suat', 'ky nam giu', 'co tuc'],
  },
  {
    id: 'cagr',
    categoryId: 'returns',
    name: { vi: 'CAGR — tăng trưởng kép hằng năm', en: 'Compound annual growth rate' },
    description: 'Tốc độ tăng trưởng bình quân mỗi năm của một khoản đầu tư.',
    level: 'basic',
    isFeatured: true,
    tags: ['cagr', 'tang truong kep', 'binh quan nam'],
  },
  {
    id: 'ty-suat-co-tuc',
    categoryId: 'returns',
    name: { vi: 'Tỷ suất cổ tức', en: 'Dividend yield' },
    description: 'Cổ tức tiền mặt một năm so với thị giá hiện tại của cổ phiếu.',
    level: 'basic',
    isFeatured: true,
    tags: ['ty suat co tuc', 'dividend yield', 'co tuc'],
  },
  {
    id: 'xirr',
    categoryId: 'returns',
    name: { vi: 'XIRR — suất sinh lợi nội tại theo ngày thực', en: 'XIRR' },
    description: 'Suất sinh lợi năm hoá từ một chuỗi dòng tiền vào ra không đều kỳ, tính đúng theo ngày thực.',
    level: 'advanced',
    tags: ['xirr', 'suat sinh loi noi tai', 'dong tien khong deu', 'irr thuc te'],
  },
  {
    id: 'loi-suat-nam-hoa',
    categoryId: 'returns',
    name: { vi: 'Lợi suất năm hoá', en: 'Annualized return' },
    description: 'Quy một lợi suất kỳ ngắn (tháng, tuần…) về mức tương đương cả năm theo lãi kép.',
    level: 'basic',
    tags: ['nam hoa', 'annualized', 'quy nam', 'loi suat ky'],
  },
  {
    id: 'loi-suat-thuc',
    categoryId: 'returns',
    name: { vi: 'Lợi suất thực sau lạm phát', en: 'Real return (Fisher equation)' },
    description: 'Sức mua thật sự tăng bao nhiêu sau khi trừ lạm phát khỏi lợi suất danh nghĩa.',
    level: 'basic',
    tags: ['loi suat thuc', 'lam phat', 'fisher', 'real return', 'suc mua'],
  },
  {
    id: 'lai-suat-hieu-dung',
    categoryId: 'returns',
    name: { vi: 'Lãi suất hiệu dụng năm (EAR)', en: 'Effective annual rate' },
    description: 'Mức lãi thật sự nhận được cả năm khi lãi được ghép nhiều lần trong năm.',
    level: 'basic',
    tags: ['ear', 'lai suat hieu dung', 'ghep lai', 'effective annual rate', 'apr'],
  },
  {
    id: 'tong-loi-suat-tai-dau-tu',
    categoryId: 'returns',
    name: { vi: 'Tổng lợi suất có tái đầu tư cổ tức', en: 'Total return with reinvested dividends' },
    description: 'Lợi suất tích luỹ nhiều năm khi cổ tức nhận được đem mua lại chính cổ phiếu đó.',
    level: 'basic',
    tags: ['tong loi suat', 'tai dau tu co tuc', 'total return', 'reinvest', 'co tuc'],
  },
  {
    id: 'loi-suat-trung-binh-hinh-hoc',
    categoryId: 'returns',
    name: { vi: 'Lợi suất trung bình hình học', en: 'Geometric mean return' },
    description: 'Mức lợi suất đều mỗi kỳ tương đương với một chuỗi 2–3 kỳ lên xuống thất thường.',
    level: 'basic',
    tags: ['trung binh hinh hoc', 'geometric mean', 'loi suat nhieu ky', 'binh quan'],
  },
  {
    id: 'irr-nien-kim',
    categoryId: 'returns',
    name: { vi: 'IRR của dòng tiền đều (niên kim)', en: 'IRR of an ordinary annuity' },
    description: 'Suất sinh lợi nội tại mỗi kỳ khi bỏ vốn một lần rồi nhận về một khoản đều đặn nhiều kỳ.',
    level: 'advanced',
    tags: ['irr', 'nien kim', 'suat sinh loi noi tai', 'annuity', 'dong tien deu'],
  },
  {
    id: 'thoi-gian-nhan-doi',
    categoryId: 'returns',
    name: { vi: 'Thời gian nhân đôi vốn', en: 'Doubling time (rule of 72)' },
    description: 'Cần bao nhiêu năm để vốn tăng gấp đôi ở một mức lợi suất kép cho trước.',
    level: 'basic',
    tags: ['nhan doi von', 'quy tac 72', 'rule of 72', 'doubling time'],
  },
  {
    id: 'loi-suat-quy-nam-theo-ngay',
    categoryId: 'returns',
    name: { vi: 'Lợi suất quy năm theo số ngày', en: 'Annualized holding period return' },
    description: 'Quy lợi suất của một lần mua bán ngắn ngày về mức tương đương cả năm.',
    level: 'basic',
    tags: ['quy nam', 'so ngay nam giu', 'annualized', 'hpr', 'luot song'],
  },
  {
    id: 'loi-suat-vuot-chuan',
    categoryId: 'returns',
    name: { vi: 'Lợi suất vượt chuẩn', en: 'Excess return' },
    description: 'Danh mục làm tốt hơn hay kém hơn mốc so sánh bao nhiêu điểm phần trăm.',
    level: 'basic',
    tags: ['vuot chuan', 'excess return', 'benchmark', 'so voi vn index', 'chenh lech'],
  },
  {
    id: 'co-lenh-rui-ro',
    categoryId: 'risk',
    name: { vi: 'Cỡ lệnh theo % rủi ro', en: 'Risk-based position size' },
    description: 'Số cổ phiếu được phép mua để một lệnh thua không vượt quá mức rủi ro đã định.',
    level: 'basic',
    isFeatured: true,
    tags: ['co lenh', 'position size', 'quan tri rui ro', 'cat lo'],
  },
  {
    id: 'sut-giam-sau-nhat',
    categoryId: 'risk',
    name: { vi: 'Mức sụt giảm sâu nhất', en: 'Maximum drawdown' },
    description: 'Khoảng rơi lớn nhất từ một đỉnh xuống đáy sau đó, đo trong cả cửa sổ quan sát.',
    level: 'basic',
    tags: ['sut giam', 'max drawdown', 'mdd', 'rui ro', 'dinh day'],
  },
  {
    id: 'sut-giam-hien-tai',
    categoryId: 'risk',
    name: { vi: 'Mức sụt giảm hiện tại', en: 'Current drawdown from peak' },
    description: 'Giá phiên gần nhất đang thấp hơn đỉnh cao nhất trong cửa sổ bao nhiêu phần trăm.',
    level: 'basic',
    tags: ['sut giam hien tai', 'current drawdown', 'duoi dinh', 'underwater', 've dinh'],
  },
  {
    id: 'var-lich-su',
    categoryId: 'risk',
    name: { vi: 'VaR lịch sử theo phân vị', en: 'Historical Value at Risk' },
    description: 'Mức lỗ một phiên mà chỉ một tỷ lệ nhỏ số phiên trong quá khứ từng vượt qua, đọc thẳng từ phân vị chuỗi lợi suất.',
    level: 'advanced',
    tags: ['var', 'value at risk', 'gia tri chiu rui ro', 'phan vi', 'mo phong lich su'],
  },
  {
    id: 'cvar-lich-su',
    categoryId: 'risk',
    name: { vi: 'CVaR — tổn thất kỳ vọng phần đuôi', en: 'Conditional VaR (expected shortfall)' },
    description: 'Mức lỗ trung bình của riêng những phiên tệ hơn ngưỡng VaR — trả lời câu "nếu ngày xấu thật sự xảy ra thì mất bao nhiêu".',
    level: 'advanced',
    tags: ['cvar', 'expected shortfall', 'ton that ky vong', 'duoi phan phoi', 'es'],
  },
  {
    id: 'do-lech-chuan-loi-suat-phien',
    categoryId: 'risk',
    name: { vi: 'Độ lệch chuẩn lợi suất theo phiên', en: 'Daily return standard deviation' },
    description: 'Mức dao động bình quân của lợi suất mỗi phiên quanh lợi suất trung bình.',
    level: 'advanced',
    tags: ['do lech chuan', 'bien dong', 'volatility', 'standard deviation', 'rui ro'],
  },
  {
    id: 'do-bien-dong-nam-hoa',
    categoryId: 'risk',
    name: { vi: 'Độ biến động năm hoá', en: 'Annualized volatility' },
    description: 'Quy độ lệch chuẩn lợi suất theo phiên về mức tương đương cả năm.',
    level: 'advanced',
    tags: ['bien dong nam', 'annualized volatility', 'sigma', 'do lech chuan nam', 'rui ro'],
  },
  {
    id: 'do-lech-chuan-ban-phan',
    categoryId: 'risk',
    name: { vi: 'Độ lệch chuẩn bán phần', en: 'Downside deviation' },
    description: 'Chỉ đo phần dao động nằm DƯỚI một ngưỡng lợi suất, bỏ qua các phiên tăng.',
    level: 'advanced',
    tags: ['downside deviation', 'do lech chuan ban phan', 'rui ro giam', 'sortino', 'nguong'],
  },
  {
    id: 'he-so-bien-thien',
    categoryId: 'risk',
    name: { vi: 'Hệ số biến thiên', en: 'Coefficient of variation' },
    description: 'Bao nhiêu đơn vị rủi ro phải chịu cho mỗi đơn vị lợi suất bình quân.',
    level: 'advanced',
    tags: ['he so bien thien', 'coefficient of variation', 'cv', 'rui ro tren loi suat'],
  },
  {
    id: 'bien-do-dao-dong-lon-nhat',
    categoryId: 'risk',
    name: { vi: 'Biên độ dao động lớn nhất trong kỳ', en: 'Peak-to-trough price range' },
    description: 'Giá đóng cửa cao nhất trong kỳ cao hơn giá đóng cửa thấp nhất bao nhiêu phần trăm.',
    level: 'basic',
    tags: ['bien do dao dong', 'dinh day', 'price range', 'cao nhat thap nhat', 'vung gia'],
  },
  {
    id: 'chuoi-phien-giam-dai-nhat',
    categoryId: 'risk',
    name: { vi: 'Chuỗi phiên giảm dài nhất', en: 'Longest losing streak' },
    description: 'Trong kỳ, cổ phiếu đã có lần giảm liên tiếp nhiều nhất bao nhiêu phiên.',
    level: 'basic',
    tags: ['chuoi giam', 'losing streak', 'phien giam lien tiep', 'ky luat', 'tam ly'],
  },
  {
    id: 'beta',
    categoryId: 'risk',
    name: { vi: 'Beta — hệ số rủi ro hệ thống', en: 'Beta coefficient' },
    description: 'Mức một cổ phiếu biến động mạnh hay yếu hơn thị trường chung, đo bằng VN-Index.',
    level: 'advanced',
    tags: ['beta', 'he so beta', 'rui ro he thong', 'capm', 'systematic risk', 'hoi quy'],
  },
  {
    id: 'ty-so-sharpe',
    categoryId: 'risk',
    name: { vi: 'Tỷ số Sharpe', en: 'Sharpe ratio' },
    description: 'Mỗi đơn vị biến động phải chịu đổi lại được bao nhiêu phần lợi suất vượt trên lãi suất phi rủi ro.',
    level: 'advanced',
    tags: ['sharpe', 'ty so sharpe', 'rui ro dieu chinh', 'risk adjusted', 'do bien dong'],
  },
  {
    id: 'ty-so-sortino',
    categoryId: 'risk',
    name: { vi: 'Tỷ số Sortino', en: 'Sortino ratio' },
    description: 'Như Sharpe nhưng mẫu số chỉ đếm phần biến động ĐI XUỐNG — phần rủi ro mà nhà đầu tư thật sự sợ.',
    level: 'advanced',
    tags: ['sortino', 'ty so sortino', 'downside risk', 'rui ro giam gia', 'do lech phan giam'],
  },
  {
    id: 'ty-so-treynor',
    categoryId: 'risk',
    name: { vi: 'Tỷ số Treynor', en: 'Treynor ratio' },
    description: 'Phần lợi suất vượt lãi suất phi rủi ro tính trên mỗi đơn vị beta — rủi ro không thể phân tán bằng cách đa dạng hoá.',
    level: 'advanced',
    tags: ['treynor', 'ty so treynor', 'beta', 'rui ro he thong', 'risk adjusted'],
  },
  {
    id: 'ty-so-thong-tin',
    categoryId: 'risk',
    name: { vi: 'Tỷ số thông tin', en: 'Information ratio' },
    description: 'Phần lợi suất thắng được chuẩn so sánh, tính trên mỗi đơn vị rủi ro phải chấp nhận để đi lệch khỏi chuẩn.',
    level: 'advanced',
    tags: ['information ratio', 'ty so thong tin', 'vuot chuan', 'benchmark', 'sai so theo doi'],
  },
  {
    id: 'ty-so-calmar',
    categoryId: 'risk',
    name: { vi: 'Tỷ số Calmar', en: 'Calmar ratio' },
    description: 'Lợi suất năm hoá chia cho mức sụt giảm sâu nhất — đo phần lãi đổi lại bằng cú đau lớn nhất đã phải chịu.',
    level: 'advanced',
    tags: ['calmar', 'ty so calmar', 'max drawdown', 'sut giam sau nhat', 'mdd'],
  },
  {
    id: 'ty-so-thang-thua',
    categoryId: 'risk',
    name: { vi: 'Tỷ số thắng/thua', en: 'Win/loss (payoff) ratio' },
    description: 'Trung bình mức tăng của các phiên tăng so với trung bình mức giảm của các phiên giảm.',
    level: 'basic',
    tags: ['thang thua', 'win loss', 'payoff ratio', 'phien tang phien giam', 'bien do'],
  },
  {
    id: 'sma-n-phien',
    categoryId: 'technical',
    name: { vi: 'Trung bình động đơn giản (SMA)', en: 'Simple moving average' },
    description: 'Giá đóng cửa bình quân của N phiên gần nhất — đường xu hướng cơ bản nhất.',
    level: 'basic',
    tags: ['sma', 'trung binh dong', 'moving average', 'ma20', 'ma50', 'duong xu huong'],
  },
  {
    id: 'ema-n-phien',
    categoryId: 'technical',
    name: { vi: 'Trung bình động luỹ thừa (EMA)', en: 'Exponential moving average' },
    description: 'Trung bình động đặt trọng số nặng hơn cho các phiên gần đây nên bám giá nhanh hơn SMA.',
    level: 'basic',
    tags: ['ema', 'trung binh luy thua', 'exponential moving average', 'ema12', 'ema26'],
  },
  {
    id: 'macd-duong-chinh',
    categoryId: 'technical',
    name: { vi: 'Đường MACD', en: 'MACD line' },
    description: 'Hiệu giữa EMA nhanh và EMA chậm — đo xem xu hướng ngắn hạn đang kéo giá đi đâu.',
    level: 'advanced',
    tags: ['macd', 'ema12 ema26', 'phan ky hoi tu', 'dong luong', 'xu huong'],
  },
  {
    id: 'macd-duong-tin-hieu',
    categoryId: 'technical',
    name: { vi: 'Đường tín hiệu MACD', en: 'MACD signal line' },
    description: 'EMA 9 phiên của chính đường MACD — mốc so sánh để bắt điểm cắt mua bán.',
    level: 'advanced',
    tags: ['macd signal', 'duong tin hieu', 'ema9', 'giao cat macd', 'histogram'],
  },
  {
    id: 'rsi-wilder',
    categoryId: 'technical',
    name: { vi: 'RSI 14 phiên (Wilder)', en: 'Relative strength index (Wilder)' },
    description: 'Chỉ số sức mạnh tương đối 0–100, đo tỷ lệ giữa đà tăng và đà giảm gần đây.',
    level: 'basic',
    isFeatured: true,
    tags: ['rsi', 'suc manh tuong doi', 'wilder', 'qua mua qua ban', 'dao dong'],
  },
  {
    id: 'roc-toc-do-thay-doi',
    categoryId: 'technical',
    name: { vi: 'Tốc độ thay đổi giá (ROC)', en: 'Rate of change' },
    description: 'Giá hôm nay cao hơn hay thấp hơn giá của N phiên trước bao nhiêu phần trăm.',
    level: 'basic',
    tags: ['roc', 'toc do thay doi', 'rate of change', 'dong luong', 'phan tram'],
  },
  {
    id: 'dong-luong-momentum',
    categoryId: 'technical',
    name: { vi: 'Động lượng (Momentum)', en: 'Momentum' },
    description: 'Chênh lệch tuyệt đối giữa giá phiên cuối và giá của N phiên trước, tính bằng đồng.',
    level: 'basic',
    tags: ['momentum', 'dong luong', 'chenh lech gia', 'da tang', 'da giam'],
  },
  {
    id: 'khoang-cach-gia-so-sma',
    categoryId: 'technical',
    name: { vi: 'Khoảng cách giá so với SMA', en: 'Price distance from SMA' },
    description: 'Giá phiên cuối đang cao hơn hay thấp hơn đường trung bình động bao nhiêu phần trăm.',
    level: 'basic',
    tags: ['khoang cach sma', 'do lech gia', 'price deviation', 'ma20', 'qua xa duong trung binh'],
  },
  {
    id: 'giao-cat-hai-duong-ma',
    categoryId: 'technical',
    name: { vi: 'Giao cắt hai đường trung bình', en: 'Moving average crossover' },
    description: 'Chênh lệch giữa SMA ngắn hạn và SMA dài hạn — dấu của nó cho biết cắt lên hay cắt xuống.',
    level: 'basic',
    tags: ['giao cat ma', 'golden cross', 'death cross', 'ma50 ma200', 'cat len cat xuong'],
  },
  {
    id: 'dai-bollinger-tren',
    categoryId: 'technical',
    name: { vi: 'Dải Bollinger trên', en: 'Upper Bollinger band' },
    description: 'Mức giá nằm trên đường trung bình đúng k lần độ lệch chuẩn của chính chuỗi giá.',
    level: 'basic',
    tags: ['bollinger', 'dai tren', 'upper band', 'bien dong', 'ky thuat'],
  },
  {
    id: 'dai-bollinger-duoi',
    categoryId: 'technical',
    name: { vi: 'Dải Bollinger dưới', en: 'Lower Bollinger band' },
    description: 'Mức giá nằm dưới đường trung bình đúng k lần độ lệch chuẩn của chính chuỗi giá.',
    level: 'basic',
    tags: ['bollinger', 'dai duoi', 'lower band', 'bien dong', 'ky thuat'],
  },
  {
    id: 'do-rong-dai-bollinger',
    categoryId: 'technical',
    name: { vi: 'Độ rộng dải Bollinger', en: 'Bollinger bandwidth' },
    description: 'Khoảng cách giữa hai dải, quy ra phần trăm của đường giữa để so được các mã.',
    level: 'basic',
    tags: ['bollinger', 'do rong dai', 'bandwidth', 'that nut', 'squeeze', 'bien dong'],
  },
  {
    id: 'atr-dao-dong-thuc',
    categoryId: 'technical',
    name: { vi: 'ATR — dao động thực trung bình', en: 'Average true range (Wilder)' },
    description: 'Biên độ một phiên thường đi được bao nhiêu đồng, đã tính cả khoảng nhảy giá so với phiên trước.',
    level: 'basic',
    tags: ['atr', 'dao dong thuc', 'true range', 'wilder', 'bien do', 'cat lo'],
  },
  {
    id: 'phan-tram-b-bollinger',
    categoryId: 'technical',
    name: { vi: '%B — vị trí giá trong dải Bollinger', en: 'Bollinger %B' },
    description: 'Giá đóng cửa đang nằm ở đâu giữa hai dải: 0% là dải dưới, 100% là dải trên.',
    level: 'basic',
    tags: ['bollinger', 'phan tram b', 'percent b', 'vi tri gia', 'ky thuat'],
  },
  {
    id: 'stochastic-k',
    categoryId: 'technical',
    name: { vi: 'Stochastic %K', en: 'Stochastic oscillator %K' },
    description: 'Giá đóng cửa đang ở đâu trong khoảng cao nhất – thấp nhất của n phiên gần nhất, tính theo phần trăm.',
    level: 'basic',
    tags: ['stochastic', 'phan tram k', 'dao dong', 'qua mua', 'qua ban', 'ky thuat'],
  },
  {
    id: 'vwap',
    categoryId: 'technical',
    name: { vi: 'VWAP — giá bình quân theo khối lượng', en: 'Volume weighted average price' },
    description: 'Giá trung bình của n phiên gần nhất, nhưng phiên khớp nhiều cổ phiếu được tính nặng hơn.',
    level: 'basic',
    tags: ['vwap', 'gia binh quan', 'khoi luong', 'volume weighted', 'ky thuat'],
  },
  {
    id: 'do-bien-dong-lich-su',
    categoryId: 'technical',
    name: { vi: 'Độ biến động lịch sử năm hoá', en: 'Annualized historical volatility' },
    description: 'Độ lệch chuẩn của lợi suất log hằng phiên, quy về mức tương đương cả năm bằng căn bậc hai số phiên.',
    level: 'advanced',
    tags: ['do bien dong', 'volatility', 'nam hoa', 'loi suat log', 'rui ro', 'ky thuat'],
  },
  {
    id: 'ty-le-khoi-luong',
    categoryId: 'technical',
    name: { vi: 'Tỷ lệ khối lượng so với trung bình', en: 'Relative volume' },
    description: 'Khối lượng phiên gần nhất gấp bao nhiêu lần khối lượng trung bình n phiên liền trước.',
    level: 'basic',
    tags: ['khoi luong', 'volume', 'thanh khoan', 'relative volume', 'dot bien', 'ky thuat'],
  },
  {
    id: 'gia-ly-thuyet-vn30f',
    categoryId: 'derivatives',
    name: { vi: 'Giá lý thuyết hợp đồng tương lai', en: 'Theoretical futures price' },
    description: 'Mức giá hợp lý của hợp đồng VN30F suy từ chỉ số cơ sở, lãi suất và cổ tức (cost of carry).',
    level: 'advanced',
    tags: ['vn30f', 'gia ly thuyet', 'hop dong tuong lai', 'cost of carry', 'futures', 'phai sinh'],
  },
  {
    id: 'basis-vn30f',
    categoryId: 'derivatives',
    name: { vi: 'Basis — chênh giá so với chỉ số', en: 'Futures basis' },
    description: 'Khoảng chênh giữa giá hợp đồng VN30F và chỉ số VN30 cơ sở, tính bằng điểm.',
    level: 'basic',
    tags: ['basis', 'vn30f', 'chenh gia', 'premium', 'discount', 'phai sinh'],
  },
  {
    id: 'lai-lo-vi-the-long',
    categoryId: 'derivatives',
    name: { vi: 'Lãi/lỗ vị thế Long', en: 'Long futures position P&L' },
    description: 'Số tiền lãi hoặc lỗ của vị thế mua hợp đồng VN30F, quy ra đồng.',
    level: 'basic',
    isFeatured: true,
    tags: ['lai lo', 'vi the long', 'vn30f', 'mua', 'pnl', 'long', 'phai sinh'],
  },
  {
    id: 'lai-lo-vi-the-short',
    categoryId: 'derivatives',
    name: { vi: 'Lãi/lỗ vị thế Short', en: 'Short futures position P&L' },
    description: 'Số tiền lãi hoặc lỗ của vị thế bán hợp đồng VN30F, quy ra đồng.',
    level: 'basic',
    tags: ['lai lo', 'vi the short', 'vn30f', 'ban', 'pnl', 'short', 'phai sinh'],
  },
  {
    id: 'so-hop-dong-toi-da',
    categoryId: 'derivatives',
    name: { vi: 'Số hợp đồng tối đa theo ký quỹ', en: 'Maximum contracts by initial margin' },
    description: 'Số hợp đồng VN30F nhiều nhất mở được với số tiền ký quỹ hiện có.',
    level: 'basic',
    tags: ['ky quy', 'so hop dong', 'margin', 'vn30f', 'ky quy ban dau', 'phai sinh'],
  },
  {
    id: 'co-vi-the-phai-sinh',
    categoryId: 'derivatives',
    name: { vi: 'Cỡ vị thế phái sinh theo % rủi ro', en: 'Risk-based futures position size' },
    description: 'Số hợp đồng được phép mở để một lệnh chạm cắt lỗ không mất quá mức rủi ro đã định.',
    level: 'basic',
    isFeatured: true,
    tags: ['co vi the', 'position size', 'quan tri rui ro', 'cat lo', 'vn30f', 'phai sinh'],
  },
  {
    id: 'don-bay-hieu-dung',
    categoryId: 'derivatives',
    name: { vi: 'Tỷ lệ đòn bẩy hiệu dụng', en: 'Effective leverage ratio' },
    description: 'Giá trị danh nghĩa của vị thế đang gấp bao nhiêu lần vốn thực có trong tài khoản.',
    level: 'basic',
    tags: ['don bay', 'leverage', 'vn30f', 'gia tri danh nghia', 'notional', 'phai sinh'],
  },
  {
    id: 'tra-gop-nien-kim',
    categoryId: 'loans',
    name: { vi: 'Trả góp niên kim', en: 'Annuity loan payment (EMI)' },
    description: 'Số tiền cố định phải trả mỗi tháng cho khoản vay trả góp dư nợ giảm dần.',
    level: 'basic',
    isFeatured: true,
    tags: ['tra gop', 'emi', 'nien kim', 'vay mua nha'],
  },
  {
    id: 'tra-gop-goc-deu',
    categoryId: 'loans',
    name: { vi: 'Trả góp gốc đều', en: 'Equal-principal loan payment' },
    description: 'Số tiền phải trả ở kỳ đầu tiên khi trả gốc đều nhau mỗi tháng.',
    level: 'basic',
    tags: ['goc deu', 'tra gop', 'du no giam dan'],
  },
  {
    id: 'lich-tra-no',
    categoryId: 'loans',
    name: { vi: 'Lịch trả nợ vay', en: 'Loan amortisation schedule' },
    description: 'Tổng số tiền lãi phải trả trong cả kỳ hạn, kèm bảng chi tiết từng kỳ.',
    level: 'basic',
    isFeatured: true,
    tags: ['lich tra no', 'tong lai', 'bang tra no', 'amortisation'],
  },
  {
    id: 'lai-kep',
    categoryId: 'savings',
    name: { vi: 'Lãi kép', en: 'Compound interest' },
    description: 'Số tiền tích luỹ khi tiền lãi được nhập vào gốc theo định kỳ.',
    level: 'basic',
    isFeatured: true,
    tags: ['lai kep', 'compound', 'tich luy'],
  },
  {
    id: 'lai-tien-gui',
    categoryId: 'savings',
    name: { vi: 'Lãi tiền gửi có kỳ hạn', en: 'Term deposit interest' },
    description: 'Tiền lãi đơn nhận được cho một khoản gửi tiết kiệm có kỳ hạn.',
    level: 'basic',
    tags: ['lai tien gui', 'tiet kiem', 'ky han', 'lai don'],
  },
  {
    id: 'tiet-kiem-muc-tieu',
    categoryId: 'savings',
    name: { vi: 'Tiết kiệm theo mục tiêu', en: 'Goal-based savings' },
    description: 'Số tiền cần gửi đều mỗi tháng để đạt một mục tiêu tài chính.',
    level: 'basic',
    tags: ['tiet kiem muc tieu', 'goal savings', 'gui dinh ky'],
  },
  {
    id: 'rut-truoc-han',
    categoryId: 'savings',
    name: { vi: 'Lãi thực nhận khi rút trước hạn', en: 'Early withdrawal interest' },
    description: 'Tiền lãi thực nhận khi rút sổ tiết kiệm trước hạn — chỉ được trả theo lãi suất không kỳ hạn, mức cụ thể tuỳ từng ngân hàng.',
    level: 'basic',
    tags: ['rut truoc han', 'lai khong ky han', 'tiet kiem', 'early withdrawal'],
  },
  {
    id: 'gui-quay-vong',
    categoryId: 'savings',
    name: { vi: 'Gửi quay vòng kỳ ngắn hay gửi kỳ dài', en: 'Rolling short-term vs long-term deposit' },
    description: 'Chênh lệch tiền cuối kỳ giữa gửi kỳ ngắn quay vòng liên tục và gửi một sổ kỳ dài.',
    level: 'basic',
    tags: ['quay vong', 'ky ngan', 'ky dai', 'tiet kiem', 'rollover', 'lai kep'],
  },
  {
    id: 'gia-von-trung-binh-dca',
    categoryId: 'investing',
    name: { vi: 'Giá vốn trung bình khi mua DCA', en: 'DCA average cost per share' },
    description: 'Giá vốn bình quân sau nhiều đợt mua với số tiền và giá khác nhau. Đợt nào không có thì nhập 0 vào cả ô tiền lẫn ô giá — đợt đó được bỏ qua.',
    level: 'basic',
    isFeatured: true,
    tags: ['dca', 'gia von trung binh', 'trung binh gia', 'average cost', 'dau tu dinh ky'],
  },
  {
    id: 'so-ky-dca',
    categoryId: 'investing',
    name: { vi: 'Số kỳ DCA để đạt mục tiêu', en: 'DCA periods to reach a goal' },
    description: 'Cần góp đều bao nhiêu tháng để khoản đầu tư định kỳ đạt số tiền mục tiêu, với lợi suất kỳ vọng cho trước.',
    level: 'basic',
    tags: ['dca', 'so ky', 'muc tieu', 'gop deu', 'dau tu dinh ky', 'periods to goal'],
  },
  {
    id: 'thue-tncn-dau-tu',
    categoryId: 'personal-tax',
    name: { vi: 'Thuế TNCN một giao dịch đầu tư trong năm', en: 'Personal income tax on an investment in a year' },
    description: 'Tổng thuế thu nhập cá nhân phải nộp trong năm cho một khoản đầu tư: thuế chuyển nhượng khi bán cộng thuế cổ tức tiền mặt.',
    level: 'basic',
    tags: ['thue tncn', 'thue dau tu', 'chuyen nhuong', 'co tuc', 'personal income tax'],
  },
  {
    id: 'diem-hoa-von',
    categoryId: 'corporate-finance',
    name: { vi: 'Điểm hoà vốn doanh nghiệp', en: 'Break-even point' },
    description: 'Cần bán bao nhiêu sản phẩm để doanh thu vừa đủ bù toàn bộ chi phí, kèm mức doanh thu hoà vốn tương ứng.',
    level: 'advanced',
    tags: ['diem hoa von', 'hoa von', 'break even', 'bep', 'dinh phi', 'bien phi', 'so du dam phi'],
  },
  {
    id: 'don-bay-tong-hop',
    categoryId: 'corporate-finance',
    name: { vi: 'Đòn bẩy tổng hợp (DOL × DFL)', en: 'Degree of total leverage' },
    description: 'Doanh thu thay đổi 1% thì EPS thay đổi bao nhiêu phần trăm, gộp cả đòn bẩy hoạt động và đòn bẩy tài chính.',
    level: 'advanced',
    tags: ['don bay tong hop', 'dtl', 'dol', 'dfl', 'don bay hoat dong', 'don bay tai chinh', 'leverage', 'eps'],
  },
];
